version: "3.9"
name: webscraper_api
services:
  api:
    build: .
    image: webscraper
    container_name: webscraper_api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=webscraper_api/server.py
      - MONGODB_URI=mongodb://mongodb:27017/webscraper
    networks:
      - webscraper
    depends_on:
      - db
    restart: always
  db:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - webscraper
    restart: always
networks:
  webscraper:
    name: webscraper
